---
name: build examples
on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  yaml_to_json_string:
    uses: ./.github/workflows/yaml_to_json_string.yml
    with:
      path: .eil.yml

  build:
    runs-on: ubuntu-latest
    needs: yaml_to_json_string
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.yaml_to_json_string.outputs.result).targets }}
        esp_idf_version:
          - v5.1
          - v5.2
          - v5.3
          - v5.4
    steps:
      - name: Check out
        uses: actions/checkout@v4


      - name: Find examples
        run: |
          EXAMPLES=`find examples -type d -maxdepth 1 -mindepth 1` >> $GITHUB_ENV

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ matrix.esp_idf_version }}
          target: ${{ matrix.target }}
          path: ${{ env.EXAMPLES }}
