---
name: build examples
on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  yaml_to_json_string:
    uses: ./.github/workflows/yaml_to_json_string.yml
    with:
      path: .eil.yml

  build:
    runs-on: ubuntu-latest
    needs: yaml_to_json_string
    strategy:
      matrix:
        target: ${{ fromJSON(needs.yaml_to_json_string.outputs.result).targets }}
    steps:
      - name: Build
        run: |
          echo ${{ matrix.target }}
