---
name: build examples
on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  build:
    strategy:
      matrix:
        idf_ver: ["v5.3"]
    runs-on: ubuntu-latest
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build examples
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          # pip install idf-component-manager ruamel.yaml idf-build-apps --upgrade
          cd examples/hello_world && idf.py build
