---
name: build examples
on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  build:
    strategy:
      matrix:
        idf_ver: ["v5.3"]
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:${{ matrix.idf_ver }}
      env:
        IDF_CLONE_SHALLOW: 1
        IDF_CLONE_SHALLOW_DEPTH: 1
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: source export.sh
        run: |
          . ${IDF_PATH}/export.sh
          env | grep "IDF_" >> ${GITHUB_ENV}
          echo "PATH=${PATH}" >> ${GITHUB_ENV}

      - name: Build examples
        shell: bash
        run: |
          cd examples/hello_world && idf.py build
