---
name: Convert YAML file to JSON string
on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string
    outputs:
      result:
        description: |
          The parsed JSON as string. Use fromJson() in steps or jobs
        value: ${{ jobs.perform.outputs.json }}

jobs:
  perform:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.result.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse YAML
        id: result
        run: |
          echo result=`ruby -e "require 'yaml'; require 'json'; doc = YAML.safe_load(File.read('.eil.yml')); doc['targets'] = doc['targets'].reject { |e| e == 'esp8266' }; puts doc.to_json"`
          cat $GITHUB_OUTPUT
